apiVersion: v1
kind: Namespace
metadata:
  name: sales-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-pod
  namespace: sales-system
spec:
  #labels para poder realizar queries
  selector:
    matchLabels:
      app: sales
  template:
    metadata:
      labels:
        app: sales
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
        - name: sales-api
          image: sales-api-image
          ports:
          # abre portas no container
          - name: sales-api
            containerPort: 3000
          - name: sales-api-debug
            containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: sales-system
spec:
  # disponibiliza um IP e portas para serem acessadas dentro do cluster
  type: ClusterIP
  selector:
    app: sales
  ports:
  - name: sales-api
    port: 3000
    targetPort: sales-api
  - name: sales-api-debug
    port: 4000
    targetPort: sales-api-debug

