apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# indica em que diretório ele vai olhar o outro arquivo kustomization.yaml
# para saber em qual arquivo o patch vai ser aplicado
- ../../base/sales-pod/
patchesStrategicMerge:
# indica qual patch será aplicado
# vai colocar tudo que tem no patch que não tem no base
- ./kind-sales-api-patch.yaml
